{{/* renovate: depName=metallb repoUrl=https://metallb.github.io/metallb */}}
{{- $version := "0.4.4" -}}

{{- with .Config.kubevip -}}
apiVersion: v1
kind: Namespace
metadata:
  name: kube-vip
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-vip
  namespace: kube-vip
spec:
  chart: kube-vip
  repo: https://kube-vip.github.io/helm-charts
  version: "{{ default "0.4.4" .version }}"
  valuesContent: |-
    config:
      address: "{{ .eip }}"
    env:
      vip_interface: "{{ default "eth0" .interface }}"
      cp_enable: "{{ default "true" .enable }}"
{{- end -}}
