name: Custom Image

on:
  push:
    tags:
      - v*
    branches:
      - main

concurrency:
  group: ci-os-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      REGISTRY_USER: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Docker runtime
        uses: docker-practice/actions-setup-docker@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Earthly build
        uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - name: Sign into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build kairos-agent
        run: earthly ./image/kairos-agent+build
      - name: Build os-image and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./image
          tags: ${{ env.REGISTRY }}/wyvernzora/kairos
