name: Lint
on:
 push:
   branches:
     - main
 pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0
      - name: Run Lint checks
        run: |
          ./earthly.sh +lint
