name: Lint
on:
 push:
   branches:
     - main
 pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - name: Run Lint checks
        run: earthly +lint
