name: Test
on:
  pull_request:
  push:

concurrency:
  group: ci-test-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        bundles:
          - kube-vip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci --push +test --BUNDLE=${{ matrix.bundles }}
