name: Test
on:
  pull_request:
  push:

concurrency:
  group: ci-test-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        bundles:
          - kube-vip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: docker-practice/actions-setup-docker@master
      - run: ./earthly.sh --ci --push +test --BUNDLE=${{ matrix.bundles }}
